cycle-days: 28
allow-claim-once-per-day: true

gui:
  title: "&6&lPREMIUM &f&lDAILY"
  bonus-button-slot: 49
  bonus-button:
    material: LIME_CONCRETE
    name: "&a&lBONUS!!"
    lore:
      - "&7사이클 보상을 모두 수령하면 받을 수 있어요."

texts:
  already-claimed-today: "&c오늘은 이미 출석 보상을 받았습니다."
  claimed: "&a{day}일차 보상 수령! (진행도: {progress}/{cycle})"
  not-available: "&c아직 수령할 수 없는 날입니다."
  bonus-ready: "&c아직 보너스를 받을 수 없습니다."
  bonus-claimed: "&b보너스 보상을 받았습니다! 새 사이클이 시작됩니다."
  open-settings: "&7설정 GUI를 열었습니다."

rewards:
  "1":
    icon:
      material: PAPER
      name: "&a1일차 보상"
      lore: []
    commands:
      - "give {player} diamond 1"
    items: []
  "2":
    icon:
      material: PAPER
      name: "&a2일차 보상"
      lore: []
    commands:
      - "give {player} emerald 2"
    items: []

bonus:
  icon:
    material: CHEST
    name: "&6보너스 상자"
    lore:
      - "&7사이클을 모두 채우면 수령!"
  commands:
    - "give {player} nether_star 1"
  items: []

sounds:
  enable: true
  click: UI_BUTTON_CLICK
  claim: ENTITY_PLAYER_LEVELUP
  bonus: UI_TOAST_CHALLENGE_COMPLETE
  error: ENTITY_VILLAGER_NO

titles:
  enable: true
  fade-in: 10
  stay: 40
  fade-out: 10
  claim:
    title: "&a{day}일차 보상 수령!"
    subtitle: "&7진행도 {progress}/{cycle}"
  bonus:
    title: "&6보너스 수령 완료!"
    subtitle: "&7새 사이클이 시작됩니다."

announce:
  enable: true
  chat:
    header: "&6&l━━━━━━━━━ &e&l공지 &6&l━━━━━━━━━"
    message-format: "&f{message}"
    show-sender: true
    sender-format: "&7From &f{sender}"
    footer: "&6&l━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  title:
    enable: true
    title: "&e&l공지"
    subtitle: "&f{message}"
  actionbar:
    enable: true
    text: "&6[공지]&f {message}"
  sound: UI_TOAST_IN

# Citizens NPC ids that open attendance GUI on right-click
citizens-links: []


# 미리보기 GUI에서 '실행: <명령>' 종이 아이템 표시 여부
preview:
  show-command-papers: false


# 보상으로 'PAPER' 아이템이 지급되지 않도록 강제 차단 (기본 false)
rewards:
  allow-paper: false
